spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: sta_mandela-brothers
            client-secret: 6414dfb0-1ed0-430b-b09a-046834aa84be
            authorization-grant-type: client_credentials
            scope:
            - bid
        provider:
          sso:
            issuer-uri: https://login.sso.az.run.withtanzu.com
