app:
  marketplace:
    url: https://sta.az.run.withtanzu.com
  agent:
    strategy: random
    user: mandela-brothers

spring:
  application:
    name: sta-spring-boot-trading-agent
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: sta_mandela-brothers
            client-secret: 6414dfb0-1ed0-430b-b09a-046834aa84be
            authorization-grant-type: client_credentials
            scope:
              - bid
        provider:
          sso:
            issuer-uri: https://login.sso.az.run.withtanzu.com

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      source: ${spring.application.name}-${random.uuid}
  tracing:
    # Set to true to forward tracing spans to a local Zipkin instance.
    enabled: false
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        # Set to true to forward metrics to a local OpenTelemetry collector.
        enabled: false
        step: 30s
logging:
  pattern:
    # Include tracing ids in log entries.
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${PORT:8082}
